name: Reusable Deploy
on: 
  workflow_call:
    inputs: 
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps: 
      - name : Get code
        uses: actions/download-artifact@v3
        with: 
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying $ uploading..."
  info: 
    runs-on: ubuntu-22.04
    steps:
      - name: Output smth
        run: echo "Smth"